
[general]
	disable_mod = false
	auto_start = false
	space_modules = false
	shadow_text = true
	animations = true
	animationSpeed = 2.0
	fontScale = 0.9
	background_color = 1867534416
	hide_debug_crosshair = false
	hide_sidebar = false
	hide_bossbar = false
	always_show_profiler = false
	always_show_tps = false

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = false
		chunk_relative_coords = false
		chunk_coords = false

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_right.lines]
		time = true
		java_version = false
		memory_usage = true
		allocation_rate = false
		allocated_memory = true
		cpu = false
		display = false
		gpu = false
		opengl_version = false
		gpu_driver = false

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		server_tick = false
		packets_sent = true
		packets_received = true

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_right.lines]
		minecraft = true

